### ISSUE TITLE
Need for `BaseQuad`, `InQuad` and `OutQuad`?

### ISSUE THREAD

**Issue by dhurlburtusa** [rdfjs/types#41]
Can someone help me understand the need for the `BaseQuad` interface? Seems like the `Quad` interface is sufficient.

What is the need for `InQuad` and `OutQuad` in `DatasetCore`, `Dataset`, `DatasetCoreFactory`, and `DatasetFactory`?

**Comment by tpluscode** [comment]
`Quad`, which is the default quad interface, limits the types of subject, predicate, object and graph it accepts using subtypes `Quad_Subject`, `Quad_Predicate`, `Quad_Object`, and `Quad_Graph` respectively. This prevents you from accidentally using the [`defaultGraph` as subject](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQKZRAGjgEQIYx4DOqMAYngMYzQCe2+hF1dcAvnAGZQQhwDkAASgATTgCsiAehi0wqIvwBQSyhAB2ReJyo0otOAF5EHYrgJ5me2ip0t9AOgCOAVzwiAFHesORqHS4ANjAA4lB4YAAWHgCU2N50DgBGgXjqANYAchB+sfG6iSlpWTmosTFAA), [blank node as property](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQKZRAGjgEQIYx4DOqMAYngMYzQCe2+hF1dcAvnAGZQQhwDkAASgATTgCsiAehi0wqIvwBQSyhAB2ReJyo0otOAF5EHYrgJ5me2ip0t9AOgCOAVzwiAFHesOARgBs8dQBrADkIEVQPAEpsbzo-QJDwyJi43QSAoLCIqOjooA), etc.

The `InQuad` and `OutQuad` are the same by default. This means that a dataset **accepts** and **contains** quads of the same type. However, an implementor may choose to use an extended model internally which adds some property, for example a pre-computed hash. Given an instance of `DatasetCore<MyQuad>`, the `add` method would only accept `MyQuad`, preventing using quads produced from other factories. This would be a nuisance from the perspective of interoperability. Instead, the implementor could accept any kinds of quad as input and add the hash dynamically so that the stored quad conforms to the internal interface. This is done by typing an implementation as `DatasetCore<MyQuad, Quad>` or even `DatasetCore<MyQuad, BaseQuad>`.

Here's that [example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRQK4EMAmAaOARdGdAZwFMYBhaUuAXzgDMoIQ4ByAASkwYCtiA9DACeYUsTYAoScAB2MUlAboAxjQCywtFjikAHgtmZiKDJkSS4cABYlrALjjEYUOQHNJtaQBtycAI5mAISO2pg+fnIMvnrAAEa+BERkMI5JJORUUKQAPJphAHwystH68YmEGTBBAHRYmAAUgVgAlBHwmJUpaV2Z1HlaZriFkp3J5LX1TWZtQA)

**Comment by tpluscode** [comment]
Hello @dhurlburtusa can we close this issue as answered or do you still find something missing?
